### ISSUE TITLE
tutorial  maven plugin

### ISSUE THREAD

**Issue by Th1aguin** [comundus/vfs-maven-plugin#8]
Can you create a simple tutorial how to use your plugin to develop in opencms? I don't know how to start or configure a project to use your plugin.

I still use webdav sincronize and its very bad.

Sorry to post it here I don't know where to ask

**Comment by veggie** [comment]
Hi @Th1aguin, 
please check out https://opencms-maven.comundus.com/. You should all the information there. If you are using OpenCms 10.5, for which the plugin is not ready yet, you might be interested in upgrading the plugin by yourself. If so, check out the following readme: https://github.com/comundus/vfs-maven-plugin/blob/master/doc/version-upgrade.md
Hope this helps.
Best regards
veggie

**Comment by Th1aguin** [comment]
Thanks man...
I can not describe how grateful am I...

I'm still using opencms 8.5.2 and now I'm trying to upgrate to 9.5 but I would like to improve  the way that I use to develop in Opencms...

Really, thank you
Sorry for the work

**Comment by veggie** [comment]
No problem. It's not so easy to find the info.
So I am closing this issue. If you have further questions. Don't hesitate to ask.
Regards
veggie
